### PR TITLE
Stub @blinkmobile/blinkmrc removing write to file

### PR DESCRIPTION
**Pull request by mymattcarroll**
### Fixed

-   Tests that do not clean up after themselves (#148)

### CODE REVIEW

**Comment by jokeyrhyme** [comment]
I wish there was a cleaner way of doing this without using `t.plan()`

**Comment by mymattcarroll** [comment]
How would you do this sort of thing in `jest` i.e. testing that a function you pass as an argument is called?

**Comment by jokeyrhyme** [comment]
Jest provides a built-in mock/spy thing: https://facebook.github.io/jest/docs/mock-functions.html

So you could pass in the spy as the updater function, then check it's `.mock.calls` value after the promise has resolved?

**Comment by jokeyrhyme** [comment]
But even without Jest, making a function that toggles a flag you can check later might be okay...

**Pull request merged**
