### PR TITLE
chore: migrate to cli-table3

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by DanielRuf** [comment]
This is not yet part of the current master. Can you explain me why this was closed and not merged?

**Comment by mymattcarroll** [comment]
Apologies, I did not see this merge request when i closed all the redundant Greenkeeper merge requests.

We will reopen, test and provide feedback in the future.

**Comment by DanielRuf** [comment]
Ah ok, didn't know this. Thanks for the clarification.

**Comment by DanielRuf** [comment]
Still not fixed. You are still using cli-table2 ;-)

**Pull request closed without merging**
